- name: Copy MongoDB repo file 
  ansible.builtin.copy:
    src: mongo.repo  
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing MongoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Update MongoDB Config
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0' 

- name: Start MongoDB
  ansible.builtin.service:
    name: Mongod
    state: restarted
    enabled: yes

#- name: Download and extract frontend 
#  ansible.builtin.unarchive:
#    src: https://github.com/stans-robot-project/mongodb/archive/main.zip
#    dest: /tmp 
#    remote_src: yes
#      # If the source is not local , you need to mention remote soruce as yes. 

- name: Download and archive file from mongodb
  ansible.builtin.include_role:
    name: common
    tasks_from: download


- name: Run mongodb file for catalogue
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
   - catalogue
   - user

#- name: Run mongodb file for user
#  community.mongodb.mongodb_shell:
#    file: "/tmp/mongodb-main/users.js"
#    idempotent: yes