- name: Demo on using shell module    
  hosts: all
  tasks: 
   - name: Running a shell commands
     shell: uptime
     register: OUT

   - name : Display uptime
     debug: 
       msg:  The display uptime {{ OUT }}

   - name : Display stdin
     debug: 
       msg:  The display uptime {{ OUT.stdout }}