- name: Configure the Yum Repos 
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install NodeJS 
  ansible.builtin.yum:
    name: "{{item}}"
    state: present  
  loop: 
    - nodejs 
    - gcc-c++  

- name: Adding Application User 
  ansible.builtin.user:
    name: roboshop 
    comment: roboshop project application user 

- name: Download and archive file from mongodb
  ansible.builtin.include_role:
    name: common
    tasks_from: download